### ISSUE TITLE
Division by zero error with fractions

### ISSUE THREAD

**Issue by ahumenberger** [Nemocas/AbstractAlgebra.jl#575]
The following piece of code works:
```julia
R, n = PolynomialRing(QQ, "n")
(n+1)//n # yields no error
```
Now, replacing the field of rationals by a fraction field yields an error:
```julia
S, _ = PolynomialRing(QQ, ["x", "y"])
F = FractionField(S)
R, n = PolynomialRing(F, "n")
(n+1)//n
```
yields
```julia
Exception (fmpq_div). Division by zero.
ERROR: Problem in the Flint-Subsystem
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] flint_abort() at /Users/ahumenberger/.julia/packages/Nemo/U6pKT/src/Nemo.jl:104
 [3] divexact(::fmpq_mpoly, ::fmpq) at /Users/ahumenberger/.julia/packages/Nemo/U6pKT/src/flint/fmpq_mpoly.jl:408
 [4] gcd(::AbstractAlgebra.Generic.Frac{fmpq_mpoly}, ::AbstractAlgebra.Generic.Frac{fmpq_mpoly}) at /Users/ahumenberger/.julia/packages/AbstractAlgebra/RaAkt/src/generic/Fraction.jl:754
 [5] content(::AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}}) at /Users/ahumenberger/.julia/packages/AbstractAlgebra/RaAkt/src/generic/Poly.jl:1557
 [6] gcd(::AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}}, ::AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}}) at /Users/ahumenberger/.julia/packages/AbstractAlgebra/RaAkt/src/generic/Poly.jl:1529
 [7] //(::AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}}, ::AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.Frac{fmpq_mpoly}}) at /Users/ahumenberger/.julia/packages/AbstractAlgebra/RaAkt/src/generic/Fraction.jl:68
 [8] top-level scope at REPL[65]:1
```

I tried to track down the problem. My conclusion was that since `canonical_unit(::FracElem)` returns the element itself (i.e. `canonical_unit(0) = 0`) we get a div by zero error in
https://github.com/Nemocas/AbstractAlgebra.jl/blob/90623491d9c3634b98563906f30b76368bdb3e59/src/generic/Fraction.jl#L754

**Comment by wbhart** [comment]
I concur. The solution is to put a zero test at the start of that function for each of the inputs and deal with it specially.

Thanks for the report.

**Comment by ahumenberger** [comment]
Seems like this is fixed in master?!

**Comment by thofma** [comment]
Hm, your second example still crashes for me. Does it work for you?

**Comment by ahumenberger** [comment]
Both is the case ;-) With `Nemo.QQ` it does not work, but with `AbstractAlgebra.QQ` it does work. I forgot that I was using Nemo when I filed the issue.

The reason why it does not fail with `AbstractAlgebra.QQ` is the following:
```julia
S, _ = PolynomialRing(AbstractAlgebra.QQ, ["x", "y"])
divexact(zero(S), zero(S)) == zero(S) # yields true
```

**Comment by thofma** [comment]
Not sure I like that behavior with `AbstractAlgebra.QQ` better.

**Comment by ahumenberger** [comment]
There are two bugs, right? The one is the one in my previous post and the other one is that gcd(::Frac, ::Frac) produces a divbyzero error in some cases.

I'm wondering why `canonical_unit(zero(QQ)) == zero(QQ)` holds. From the name itself I would expect that `canonical_unit` returns a unit for the corresponding ring/field. What am I missing here?

**Comment by thofma** [comment]
Yes, there are two bugs. The first in the `gcd` call, which should do some zero handling.

The second bug comes from `canonical_unit(x::FieldElem) = x`, which is wrong for zero as you noticed.

**Comment by fieker** [comment]
On Tue, Apr 28, 2020 at 08:11:48AM -0700, thofma wrote:
> Not sure I like that behavior with `AbstractAlgebra.QQ` better.

THis is part of julia llowing 1//0 and other rationals with 0
denominator. In numerics this is aparently used to model various
infinities.
I vetoed this for Oscar. I can see the algebraist screeming the first
time divison by zero is legal..

**Comment by thofma** [comment]
Yes, but they don't allow to `div` with zero:
```julia
julia> div(1//1, 0//1)
ERROR: DivideError: integer division error
Stacktrace:
 [1] div at ./int.jl:232 [inlined]
 [2] div(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:361
 [3] top-level scope at none:0
 [4] eval(::Module, ::Any) at ./boot.jl:328
 [5] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
 [6] run_backend(::REPL.REPLBackend) at /home/thofmann/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [7] top-level scope at none:0
```
Although this works:
```julia
julia> (1//1)//(0//1)
1//0
```

**Comment by ahumenberger** [comment]
There seems to be a massive inconsistency:

```julia
R, _ = PolynomialRing(QQ, "n")
S, _ = PolynomialRing(QQ, ["x", "y"])
FR = FractionField(R)
FS = FractionField(S)


divexact(zero(QQ), zero(QQ)) # error
divexact( one(QQ), zero(QQ)) == Inf

divexact(zero(R), zero(R)) # error
divexact( one(R), zero(R)) # error

divexact(zero(S), zero(S)) == zero(S)
divexact( one(S), zero(S)) # error


divides(zero(QQ), zero(QQ)) # false
divides( one(QQ), zero(QQ)) # false

divides(zero(R), zero(R)) # true
divides( one(R), zero(R)) # false

divides(zero(S), zero(S)) # true
divides( one(S), zero(S)) # false


zero(QQ)//zero(QQ) # error
 one(QQ)//zero(QQ) == Inf

zero(R)//zero(R) # error
 one(R)//zero(R) # error

zero(S)//zero(S) # error
 one(S)//zero(S) # error

zero(FR)//zero(FR) # error
 one(FR)//zero(FR) # error

zero(FS)//zero(FS) == Inf
 one(FS)//zero(FS) != Inf
```

**Comment by thofma** [comment]
So first of all, there is not much we can do about the behaviour of `QQ` and `//`. Honestly, I don't think the behaviour makes much sense. Makes Rationals useless for all symbolic operations. Also
```julia
julia> one(QQ)//zero(QQ) == Inf
true
```
is misleading, since
```julia
julia> one(QQ)//zero(QQ) 
1//0
```

But I totally agree, that we should make `divexact`, `divides` and `//` (where we can) consistent.

I personally would be in favor to always throw an error if the second argument for `divexact`, `divides` and `//` is zero. Indepdent of what the first argument is. FWIW, this is also the behaviour of Magma.

This would mean a slight inconsistency with `QQ(1)//QQ(0)`, but I don't care too much about this one.

If @fieker and @wbhart agree, we can move towards this direction.

**Comment by fieker** [comment]
On Thu, Apr 30, 2020 at 02:28:26AM -0700, thofma wrote:
> So first of all, there is not much we can do about the behaviour of `QQ` and `//`. Honestly, I don't think the behaviour makes much sense. Makes Rationals useless for all symbolic operations. Also
> ```julia
> julia> one(QQ)//zero(QQ) == Inf
> true
> ```
> is misleading, since
> ```julia
> julia> one(QQ)//zero(QQ) 
> 1//0
> ```
> 
> But I totally agree, that we should make `divexact`, `divides` and `//` (where we can) consistent.
> 
> I personally would be in favor to always throw an error if the second argument for `divexact`, `divides` and `//` is zero. Indepdent of what the first argument is. FWIW, this is also the behaviour of Magma.
> 
> This would mean a slight inconsistency with `QQ(1)//QQ(0)`, but I don't care too much about this one.
> 
> If @fieker and @wbhart agree, we can move towards this direction.
> 
In AbstractAlgebra, the Julia-QQ: I do not care, I plan to never use
them and the behaviour of Rational{BigInt} is outside our control.

For fmpq, the Nemo-QQ: I'd strongly follow the algebra: division by 0 is
one of the all-time-hard No-Nos. Any form of division by 0 should throw
an error

**Comment by wbhart** [comment]
Much of this will get fixed as I work through the Oscar stuff. I didn't finish working on QQ yet I don't think.

I'm not sure about divides(0, 0). We previously discussed this and decided that it should return (true, 0). It'd be a shame to go back on that decision after I put so much effort into the ZZ stuff in Oscar.

**Comment by fieker** [comment]
On Thu, Apr 30, 2020 at 02:37:19AM -0700, wbhart wrote:
> Much of this will get fixed as I work through the Oscar stuff. I didn't finish working on QQ yet I don't think.
> 
> I'm not sure about divides(0, 0). We previously discussed this and
> decided that it should return (true, 0). It'd be a shame to go back on
> that decision after I put so much effort into the ZZ stuff in Oscar.
> 
We can argue both ways, and divides actually can be argued here.
I'd be happy either way

**Comment by wbhart** [comment]
Hmm. Maybe we didn't actually decide this. I just looked and there are no test cases for divides in Oscar. So maybe we never reached agreement.

Anyhow, divides(a, b) means the following: there exists an element c of the ring such that a = b*c. The only decision to be made is if you want to require it to be a unique element c. But that is not in any textbook definition I am aware of. So 0 divides 0, usually.

Sage returns true, for what it's worth. I think Magma's IsDivisibleBy is really a different concept. It really means you can divide a by b, which of course should not be allowed if b is 0.

**Comment by ahumenberger** [comment]
It might be confusing if `divides` returns true, but `divexact` throws an error. However I get the different perspectives.

Coming back to the original issue: We agree that `divexact` should throw an error if the denominator is 0, right? Then there is a zero test missing in case of MPoly; after fixing that, the original example should throw an error for AbstractAlgebra.QQ and Nemo.QQ.
The second question is how `canonical_unit` should behave. Right now, for Fraction it's just the identity function. Shouldn't it be something like `canonical_unit(a::FracElem) = isunit(a) ? a : one(a)`?

**Comment by wbhart** [comment]
divexact should definitely raise an exception upon division by zero.

I guess you could change canonical_unit to that definition for fractions.

**Comment by ahumenberger** [comment]
canonical_unit is also used in the gcd computation for fractions which causes this issue:
https://github.com/Nemocas/AbstractAlgebra.jl/blob/90623491d9c3634b98563906f30b76368bdb3e59/src/generic/Fraction.jl#L749-L757

I don't think it's enough to just change canonical_unit for fractions. The problem is that if you have a nested ring/field such as
```julia
S, _ = PolynomialRing(QQ, ["x", "y"])
F = FractionField(S)
R, n = PolynomialRing(F, "n")
```
then canonical_unit will be propagated down to QQ. Therefore, also Nemo.QQ would have to be changed.

**Comment by wbhart** [comment]
It's not at all clear to me that the code there is correct. I don't see why one should be able to divide the numerator and denominator by different values and still get a correct answer. From my perspective line 754 should be

```
n = divexact(n, canonical_unit(d))
```

But I haven't analysed it very closely.

**Comment by fieker** [comment]
On Fri, May 01, 2020 at 10:02:58PM -0700, ahumenberger wrote:
> It might be confusing if `divides` returns true, but `divexact` throws an error. However I get the different perspectives.
> 
> Coming back to the original issue: We agree that `divexact` should throw an error if the denominator is 0, right? Then there is a zero test missing in case of MPoly; after fixing that, the original example should throw an error for AbstractAlgebra.QQ and Nemo.QQ.
> The second question is how `canonical_unit` should behave. Right now, for Fraction it's just the identity function. Shouldn't it be something like `canonical_unit(a::FracElem) = isunit(a) ? a : one(a)`?

as a fall-back, generically: yes. In all cases: why? we might want to do
different normalisations (e.g. in Q(t): integral polynomials, monic
denominator, ...) unless we need to define this for all rings now, I'd
use your suggestions as a fall-back, but allow different behaviour

**Comment by wbhart** [comment]
Note that canonical_unit(a::FracElem) is for a whole fraction, not for the numerator and denominator. I took the question as asking why it returned zero for an input of zero, i.e. that isunit(a) just returns true when nonzero in this case.
